branch-defaults:
  main:
    environment: Civix-env
    group_suffix: null
environment-defaults:
  civix-prod:
    branch: null
    repository: null
global:
  application_name: civix
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 24
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
